<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.5" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorBase.CRUD\BlazorBase.CRUD.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Pages\Ressource1.de.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Pages\Ressource1.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
